//Script for Kasus03
monogatari.script ({
	'Kasus03': [
		'show background #000',
		'nvl Kasus03',
		'nvl Pembunuhan di Rumah Maneken Lilin',
		'show scene 0803',
		'show background house_firdaus',
		'id Sepulang sekolah mengingat akhir pekan, aku dan Firdaus merencanakan jalan-jalan sehingga aku menunggu di depan rumahnya.',
		'id Dia menunjukkan rumahnya sepulang sekolah pada hari Senin tanggal 15 Juli yang lalu, mengingat kami kebetulan pulang bersamaan.',
		'id Setelah menunggu cukup lama, Firdaus keluar dari rumahnya. Dia memakai kemeja biru dengan garis putih.',
		'id Dia meminta maaf karena aku menunggu lama, padahal tidak apa-apa bagiku.',
		'id Dia kemudian menanyakan ke mana tujuan pergi, padahal dia yang mengajakku.',
		'id Bagaimana kalau ke Rumah Maneken Lilin? Tempat itu sangat terkenal.',
		'fir Ide bagus! Aku belum pernah ke sana juga sebelumnya.',
		'id Nah, berarti kita menemukan tujuannya.',
		'fir Ayo kita ke sana!',
		'id Eits, tunggu dulu. Katanya jalan-jalan, tapi kok lari?',
		'fir Baiklah.',
		'show background city_hallway',
		'id Saat itu kami berbicara tentang pakaian yang kami kenakan. Dia memuji pakaianku.',
		'id Aku saat itu memakai baju kaos putih namun dengan jubah, serta topi bundar coklat di kepalaku. Gaya yang sederhana ini sangat kusukai untuk dibawa jalan-jalan.',
		'id Aku mengatakan bahwa pakaian ini pemberian orang. Sampai saat itu aku belum tahu siapa yang memberi.',
		'fir Benarkah? Andai aku punya seperti itu.',
		'id Kurasa masih banyak yang seperti ini di rumah. Jika kau mau, aku bisa memberikannya.',
		'fir Ah, tidak perlu. Kurasa yang kupakai sekarang adalah pakaian kesukaanku.',
		'id Dan itu bagus.',
		'id Sejak saat itu, kami hanya diam, seakan kehabisan topik pembicaraan sampai kami tiba di tujuan.',
		'show background museum_gate',
		'Firdaus dengan begitu percaya dirinya menanyakan satpam di sana.',
		'fir Pak? Ini Rumah Maneken Lilin kan?',
		'id Kamu kenal beliau?',
		'fir Kalau gak salah nama beliau Wawan. Beliau katanya dulu pernah menjadi satpam di sekolahan kita.',
		'id Aku mengangguk, dan kami pun memasuki gerbang yang dihiasi mawar itu.',
		'show background museum_door',
		'ri Halo Muhammad Idris dan Ahmad Firdaus, namaku Rina dan selamat datang di Rumah Maneken Lilin!',
		'id Bagaimana Anda bisa tahu nama kami?',
		'ri Sebentar lagi kalian akan mengetahuinya, jadi silakan masuk.',
		'show background museum_main',
		'id Kami pun masuk, dikagumkan oleh banyak maneken lilin. Beberapa di antaranya ada yang kukenal seperti walikota Sukamawar ini, dan–',
		'fir Kakakku....',
		'id Dia kakakmu kan Firdaus? Aku turut berduka cita atas meninggalnya, dia sangat berjasa dalam mengharumkan Sukamawar.',
		'id Membuatkan gerbang Anda?',
		'id Bukan itu maksudnya Idris. Dia dulu memenangkan olimpiade di Jepang. Iya kan Firdaus?',
		'ri Karena kalian sepertinya baru berkunjung ke sini, sebaiknya kuperlihatkan proses pembuatannya.',
		'fir Benarkah?',
		'ri Tentu! Mari ikut aku.',
		'id Oh ya, bukankah Anda mau memberitahu, kenapa Anda tahu nama kami?',
		'ri Astaga, aku lupa!',
		'id Kami terus berjalan dan sampai di bagian pembuatan.',
		'ri Tapi sebelum itu, perkenalkan dulu. Ini anak-anakku, yang ini namanya Manunggal.',
		'ri Yang ini namanya Dwi.',
		'ri Dan yang ini namanya Tri.',
		'ri Kami bisa mengenal kalian karena bekerja sama dengan wali kota, meneliti dengan detail setiap warga kota maupun orang yang hanya bekerja di Sukamawar ini, sehingga dapat membuatnya secara persis.',
		'Idris dan Firdaus kagum.',
		'ri Nah, sekarang kebetulan kami memproses maneken kalian. Kalau mau, kami juga akan membuatkan maneken duplikat, siapa tahu kalian ingin meletakkannya di depan rumah.',
		'id Tidak perlu, taman mawar di depan rumah kami sudah cukup bagus.',
		'ri Kamu Tri, kamu sedang membuat apa? Kok berbeda dari yang lain?',
		'tri Ini namanya <a href="https://id.wikipedia.org/wiki/Thirsos"><i>Thyrsos</i></a>.',
		'dwi Apa itu Thyrsos?',
		'ma Semacam dinosaurus kah?',
		'Dwi dan Manunggal menertawakan.',
		'tri Ini tongkat, bodoh!',
		'Tri kesal sambil membanting buatannya. Tri kemudian pergi, sepertinya dia merajuk.',
		'id Aku merasakan sesuatu kejanggalan, namun tidak tahu itu apa.',
		'ri Kalian sih....',
		'Rina kemudian pergi menemui Tri. Entah apa yang mereka bicarakan, tapi Tri sepertinya menolak ajakan mbak Rina, dia mulai menjauh sampai tak terlihat olehku.',
		'dwi Tunggu dulu, di mana pisauku yang satunya?',
		'ma Yang kecil itu bukan? Mungkin di kamarmu? Aku tadi melihatmu membuat-buat sesuatu.',
		'dwi Oh iya juga ya, kalau begitu aku ke sana dulu.',
		'ri Maafkan yang barusan, Tri memang sensitif.',
		'fir Tidak apa, tapi aku juga penasaran gimana hasil dari manekenku.',
		'ri Aku yang akan melanjutkan pembuatan maneken itu.',
		'fir Tidak mungkin.',
		'ri Ingatlah bahwa aku pemilik rumah ini. Sudah seharusnya aku juga bisa membuat maneken.',
		'Rina mengerjakan pembuatan maneken dengan waktu yang cepat dan itu membuat Idris dan Firdaus kagum.',
		'ri Nah, sudah jadi.',
		'id Firdaus terlihat kagum. Dia memegang maneken itu. Memang belum jadi sepenuhnya karena bisa saja dicat nanti, tapi hasil yang ada ini saja sudah menakjubkan kami.',
		'id Kenapa Dwi lama sekali?',
		'fir Benar juga.',
		'id Tiba-tiba kami mendengar suara teriakan, sepertinya suara Tri. Mbak Rina kemudian berlari menuju sumber suara, aku dengan sontak mengikuti beliau.',
		'show background door_bedroom1',
		'id Sehingga sampailah kami di sebuah kamar, Tri yang duduk di lantai dengan muka yang pucat menunjuk ke dalam pintu yang sudah terbuka.',
		'show background room_bed1',
		'id Mbak Rina dan aku melihat ke dalam, dan ruang itu terbakar. Dan yang lebih mengejutkan lagi, Dwi tergantung dengan dada tertusuk pisau oleh tangannya, dan dia memasang sayap.',
		'Kemudian datanglah Firdaus dan Manunggal yang berlari juga. Tak lama setelah itu, datanglah pak Wawan dengan membawa handuk basah.',
		'Tak lama kemudian, api berhasil dipadamkan. Setelah itu, pak Wawan memberi isyarat kepada Manunggal untuk melepas tali yang menjerat leher Dwi. Manunggal yang sepertinya paham, mengangguk kemudian mendekati Dwi.',
		'Tap!',
		'id Manunggal dengan refleksnya mengangkat kaki, dan dia memandangi Dwi. Kuperhatikan sayap itu, sepertinya terbuat dari lilin. Ruangan yang panas itu nampak membuatnya meleleh.',
		'Manunggal mengambil kursi, menaikinya dan melepaskan sayap yang dipasang Dwi dahulu. Mbak Rina menyambutnya perlahan karena terlihat masih panas kemudian pergi ke ruang pembuatan.',
		'Sementara itu, Manunggal berhasil menurunkan Dwi dengan bantuan pak Wawan. Setelah berhasil diturunkan, Manunggal mencabut tusukan pisau itu dengan tangannya yang masih mengenakan sarung.',
		'show background door_bedroom1',
		'ma Ya, ini pisau yang dia cari tadi.',
		'ma Mungkin ia merasa bersalah melukai perasaanmu, Tri, sehingga membunuh dirinya.',
		'tri Seharusnya hal itu tidak perlu, aku sudah memaafkannya.',
		'fir Seandainya dia bunuh diri, kenapa harus seribet ini?',
		'ri Perlukah kita menelpon polisi?',
		'Pak Wawan sontak memberi isyarat <i>jangan</i>. Kepala beliau yang menggeleng berkali-kali dan tangan yang melambai. Aku sangat heran dengan beliau.',
		'Firdaus kemudian menyarankan untuk menelepon ambulans saja, agar jasad Dwi dapat diautopsi.',
		'ri Ide bagus!',
		'id Aku salut dengan saran Firdaus. Kami bisa mengetahui apakah Dwi memang bunuh diri atau dibunuh dengan hal tersebut.',
		'show background museum_gate',
		'Berselang beberapa menit, datanglah ambulans.',
		'show background museum_door',
		'id Pak Wawan dan Manunggal mengangkat Dwi, aku dan Firdaus mengikuti mereka sampai di depan pintu.',
		'show background museum_gate',
		'Para perawat membukakan pintu ambulans sementara pak Wawan dan Manunggal memasukkan Dwi ke dalam.',
		'show background museum_door',
		'Manunggal nampak kelelahan, dan dia langsung mencari ibunya. Dia bertanya kepada kami.',
		'fir Entahlah, barusan beliau masih di ruang utama.',
		'ma Oh ya? Kalau begitu, aku mencarinya dulu.',
		'Manunggal masuk lagi ke rumah, diikuti pak Wawan.',
		'id Aku mendekati para perawat yang berada di ambulans. Firdaus hanya mengikutiku.',
		'id Saya meminta orang ini diautopsi secepatnya, karena saya ingin tahu penyebab kematiannya.',
		'ika Kami usahakan, tapi kemana kami akan menyatakan hasil autopsi?',
		'Firdaus sambil merogoh sakunya dan mengeluarkan ponsel.',
		'fir Kalian bisa meneleponku di nomor ini.',
		'Firdaus akan menyebutkan nomornya. Perawat itu meminjam ponsel sang supir sementara menyimpan nomor yang disebutkan Firdaus.',
		'Urusan sudah selesai. Pintu ambulans ditutup dan mereka pun pergi.',
		'id Kamu bawa ponsel?',
		'fir Tentu, aku selalu membawanya bersamaku. Ada apa memangnya?',
		'id Tidak apa-apa, hanya bertanya.',
		'id Kami berdiskusi sebentar. Aku menanyakan apakah kami akan pulang, apalagi setelah orang-orang di rumah ini berada di dalam. Namun Firdaus sepertinya masih ingin melihat-lihat.',
		'id Baiklah, kalau begitu kita masuk lagi.',
		'show background museum_main',
		'id Kami mulai berjalan di rumah ini. Firdaus terlihat masih semangat, dengan berjalan lebih dahulu dariku.',
		'id Aku mulai memerhatikan secara perlahan, ternyata mereka membuat ruang-ruang khusus untuk sebuah rekayasa adegan, seperti pidato pertama walikota, pembangunan taman-taman mawar. ',
		'id Ada juga ruangan yang berisi patung Zeus dan Daedalus.',
		'show background museum_room',
		'Anehnya, dari jauh ada sebuah ruangan, di dalamnya maneken seukuran manusia yang begitu mirip dengan Manunggal, duduk di kursi, di dekatnya ada maneken seukuran manusia yang begitu mirip Pak Wawan memegang katana.',
		'show background museum_main',
		'Firdaus benar-benar memerhatikannya.',
		'show background museum_room',
		'id Tiba-tiba maneken pak Wawan bergerak, aku tersadar mereka bukanlah maneken.',
		'Pak Wawan mulai mengayunkan pedangnya ke belakang. Ayunan itu mengarah tepat kepada Manunggal.',
		'Srak!',
		'Tebasan itu langsung memenggal leher Manunggal, kepalanya terpental ke dinding dengan darah berserakan di mana-mana.',
		'id Pak Wawan memandangiku, dan melempar katana-nya ke lantai. Aku yang melihat itu agak gemetar, namun Firdaus hanya berdiri di sana, seperti kehilangan pikirannya.',
		'Kemudian Wawan berlari dan menghilang entah kemana.',
		'show background museum_main',
		'ri Ada apa?',
		'Rina sekarang di ruang tengah. Dia keheranan dengan Idris dan Firdaus yang memandang sebuah ruangan.',
		'show background museum_room',
		'Rina kemudian mendekati ruangan itu, dan berteriak ketika melihat dalamnya. Dia langsung pingsan.',
		'Datanglah Tri berusaha menyadarkan ibunya.',
		'tri Kenapa kalian diam saja? Bantulah aku!',
		'show background museum_main',
		'Firdaus mulai sadar.',
		'show background museum_room',
		'Firdaus juga membantu menyadarkan setelah melihat Rina yang pingsan.',
		'id Entah kenapa, aku memerhatikan Tri. Wajahnya seperti ... begitu berkeringat.',
		'id Ada apa dengan wajahmu?',
		'tri Aku memakai pelembap wajah, memangnya kenapa?',
		'id Tidak apa-apa.',
		'tri Kamu ini aneh, haha.',
		'show background museum_main',
		'id Kemudian aku melihat pak Wawan seperti datang dari kamar mandi, dia berjalan dengan tangan yang basah secara santai menuju posnya. Aku memerhatikannya selama berjalan.',
		'id Aku kembali merasakan kejanggalan, dan aku tidak tahu itu apa.',
		'show background museum_room',
		'id Aku melihat Mbak Rina siuman.',
		'ri Apa yang terjadi di ruangan itu barusan?',
		'tri Aku juga penasaran.',
		'id Aku menceritakan kembali apa yang barusan kulihat. Mbak Rina dan Tri terkejut. Setelah itu aku menjauh, karena aku ingin menanyakan pak Wawan beberapa pertanyaan.',
		'show background museum_gate',
		'id Apa alasan Anda tidak membolehkan kami menelepon polisi saat menemukan jasad Dwi?',
		'id Aku juga memerhatikan posnya, seperti ada monitor kecil yang menampilkan rekaman CCTV dari berbagai sudut di rumah ini.',
		'id Perdebatan keras sempat terjadi, tapi aku memilih mengalah dan aku hanya meminjam saputangan.',
		'show background museum_room',
		'id Setelahnya aku menyembunyikan sapu tangan itu dan dengan berani masuk ke ruangan pembunuhan sadis tadi.',
		'id Aku juga meminta Firdaus agar mengalihkan perhatian Mbak Rina dan Tri sementara aku di sana.',
		'id Ternyata Manunggal dipakaikan kepala maneken yang dicat sedemikian rupa sehingga mirip dengan wajahnya.',
		'id Aku melepas kepala maneken itu dan melap wajah Manunggal. Aku yakin hal sesederhana ini akan membantuku dalam kasus ini.',
		'show background museum_main',
		'id Aku kembali bersama mereka, kemudian menanyakan beberapa hal.',
		'id Aku memulainya dengan Mbak Rina.',
		'id Jawaban dari semua pertanyaanku dapat disimpulkan bahwa beliau masuk ke kamar untuk melupakan sejenak apa yang terjadi kepada Dwi. Dia kemudian keluar, melihat ruangan pembunuhan itu dan terkejut melihat Manunggal.',
		'id Aku mulai bertanya kepada Tri. Hal pertama yang kutanyakan adalah tentang penemuan Dwi, mengingat dia adalah orang pertama yang menemukannya.',
		'tri Aku saat itu ingin mengambil sesuatu dari kamarnya, ternyata pintunya tertutup, padahal biasanya dia membuka pintunya. Ketika kubuka, dia sudah tergantung di sana.',
		'id Aku kemudian menanyakan tentang Manunggal. Ketiadaannya saat kejadian menjadi salah satu hal yang aku curigai.',
		'tri Aku di kamarku, tadinya aku ingin menemui seseorang, makanya aku memakai pelembap wajah. Ternyata baru saja selesai, aku mendengar ibu berteriak dan ke sinilah aku.',
		'id Begitukah? Huft....',
		'Ponsel Firdaus berdering, dia merogoh sakunya. Dia menjawab telepon itu, dan menyerahkannya pada Idris.',
		'id Terima kasih.',
		'id Sekarang sudah jelas pelakunya.',
		'id Pak Wawan, ke sini!',
		'Firdaus cukup terkejut.',
		'fir Sudah kuduga Pak Wawan pelakunya. Apalagi dengan bukti bahwa pak Wawan tahu kamar Dwi terbakar entah dari mana dan membunuh Manunggal tepat di depan mataku.',
		'wa Sayang sekali, bukan aku',
		'fir Lalu, siapa?',
		'id Tri.',
		'Semua terkejut akan ucapan Idris.',
		'tri Apa alasanmu menuduhku?',
		'Dari situlah Idris memulai pemaparan, yang disebutnya sebagai deduksi.',
		'id Pertama, aku menjelaskan dari hasil autopsi Dwi yang baru saja disampaikan.',
		'id Dwi meninggal karena tusukan pisau tepat mengenai jantungnya. Seandainya dia benar-benar bunuh diri, seharunya menggantung leher sudah cukup. Tidak mungkin seribet itu.',
		'Tri hanya diam, Idris melanjutkan pemaparannya.',
		'id Aku menjelaskan bahwa kecurigaanku dimulai saat pembuatan Thrysos itu. Seharusnya tongkat itu terbuat dari kayu, apalagi ketika kami melihat bahwa podium dari rekayasa adegan pidato pertama walikota tetap terbuat dari kayu. Aku meyakini bahwa saat itulah Tri mengambil pisau Dwi dan membawa ke kamarnya.',
		'id Kebetulan sekali sebelum hal itu terjadi, Dwi mungkin membuat sesuatu di kamarnya dan menggunakan pisau itu. Ketika pisaunya menghilang, dia akan menyangka bahwa masih ada di dalam kamarnya.',
		'id Ketika dia masuk ke kamarnya, dia berhasil menemukan pisaunya. Di saat itulah kamu mencekik lehernya. Dia mencoba melawan dengan pisau itu. Ternyata kamu itu sebenarnya kuat dan mengarahkan pisau itu ke jantung dari Dwi.',
		'id Aku menduga bahwa sesuatu yang sebelumnya dibuat oleh Dwi adalah sayap itu, Tri memintanya untuk membuatkan tanpa memberitahukan apa tujuannya.',
		'id Ketika kamu mengetahui bahwa ternyata sayap itu selesai dibuat, tiba-tiba kamu memiliki ide ingin menjadikan Dwi bunuh diri sebagai Icarus, dewa dalam mitologi yunani. Dia mendapatkan sayap dari lilin, namun semakin tinggi dia terbang, sayapnya meleleh.',
		'id Kamu tidak tahu cara agar terlihat seperti bunuh diri sekaligus menerbangkannya, maka kamu gantung tali yang terikat di lehernya tadi. Kamu juga tidak tahu cara melelehkan lilin selain membakar ruangan itu.',
		'id Pilihan membakar ruangan itu, aku menduganya entah karena Tri masih iba dengan Dwi atau ingin menyelamatkan sayapnya. Kesalahan cara ini hanya satu, dan dibuktikan dengan hasil autopsi itu.',
		'fir Lalu bagaimana dengan pak Wawan, dari mana dia tahu kamar Dwi terbakar?',
		'id Di pos beliau ada monitor CCTV, beliau walau berdiam di sana tapi selalu memerhatikan semua kamar, kecuali kamar Mbak Rina dan Dwi. Dan anehnya, rekaman kejadian kedua pembunuhan itu tidak tertangkap kamera.',
		'tri Bagaimana dengan Manunggal?! Aku sudah bilang aku di kamarku!',
		'id Kamu berbohong! Kamulah pembunuhnya!',
		'id Manunggal sebenarnya sudah tidak sadarkan diri sebelumnya sehingga dengan mudahnya kamu memasangkan replika kepalanya yang terbuat dari lilin. Aku yakin, kamu juga memakai maneken lilin Pak Wawan untuk menipu kami dalam pembunuhan itu dan menyimpannya di kamar.',
		'id Oleh karena itulah wajahmu lembap, karena kamu memasang bagian kepala itu sudah lama.',
		'Emosi Idris memuncak saat itu, namun dia memilih mengakhiri analisanya.',
		'id Baiklah, aku rasa itu cukup.',
		'ri Benarkah itu Tri?',
		'tri Ya, aku pelakunya. Semua yang dia katakan itu benar.',
		'Mbak Rina dan Firdaus terkejut.',
		'fir Mengapa kamu melakukannya?',
		'tri Mereka tidak pernah menghargaiku! Ketika aku membuat yang kuinginkan, mereka selalu menghinaku!',
		'tri Biarkan aku bercerita. Dulu aku pernah membuat maneken lilin Dionysus–',
		'id Dewa Anggur?',
		'tri Ya, dan mereka menghancurkannya!',
		'tri Aku mencoba mengenang maneken lilin itu dengan membuat tongkatnya. Dan itu pun tetap dihina mereka.',
		'Suasana hening sesaat.',
		'tri Aku tidak berbohong ketika berkata ingin bertemu seseorang. Aku akan bertemu polisi dan menyerahkan diri.',
		'Idris yang skeptis memilih menelepon polisi menggunakan ponsel Firdaus yang masih di tangannya.',
		'show background museum_gate',
		'Beberapa menit kemudian datanglah mobil polisi. Idris, Firdaus, dan Rina mengiringi Tri berjalan menuju ke sana. Dia benar-benar menyerahkan diri.',
		'Sebelum mereka pergi, Idris mereka mengambil barang-barang bukti, dari pisau Dwi yang ternyata masih berada di tangan Manunggal sampai maneken lilin Pak Wawan yang dipakai oleh Tri.',
		'id Anda punya sapu tangan lagi?',
		'kur Ada, kebetulan tak terpakai, untuk apa?',
		'id Ada bukti kuat untuk kejahatan Tri. Jika cairan di sapu tangan itu bercampur dengan lilin, maka hal yang di wajah Tri sama dengan wajah Manunggal, yang berada di sapu tangan ini.',
		'Idris menyerahkan sebuah sapu tangan',
		'Polisi itu mengeluarkan sapu tangannya, dan menyapukannya ke wajah Tri. Mereka kemudian pergi.',
		'show background museum_door',
		'Idris melihat wajah Mbak Rina bersedih.',
		'id Ada apa?',
		'ri Sekarang, aku sendirian di rumah. Suamiku sudah lama meninggalkanku, dan dia belum kembali.',
		'ri Perlukah kututup rumah ini?',
		'fir Jangan! Anda bisa menjadikannya sebagai museum!',
		'id Benar juga, museum belum ada di kota Sukamawar ini bukan?',
		'Mbak Rina menerima saran Idris dan Firdaus. Namun beliau tetap memilih menutup sementara, untuk membersihkan ruang pembunuhan Dwi dan Manunggal. Beliau berjanji untuk membuka kembali setelah jenazah Dwi dan Manunggal dimakamkan.',
		'fir Kabari kami.',
		'Ucapan Firdaus itu membuat Mbak Rina tersenyum. Beliau menjawabnya dengan anggukan kemudian masuk ke dalam rumah dan meminta Pak Wawan membantunya.',
		'Setelah itu, Idris dan Firdaus sepakat untuk pulang kali ini, daripada mengganggu mereka. Lagipula mereka sudah melihat semuanya sehingga Firdaus juga merasa sudah cukup.',
		'show background museum_gate',
		'Satu pekan setelah kejadian itu, Idris dan Firdaus kembali karena diundang oleh Mbak Rina. Firdaus memberitahukannya kepadaku. Ketika kami sampai di sana, tempat itu menjadi ramai, mengingat dulu hanya kami berdua yang mengunjungi.',
		'Terlihat banyak orang berswafoto di sana. Dan yang unik adalah, maneken lilin keluarga Mbak Rina.',
		'fir Siapa pria yang diwakili maneken lilin itu?',
		'id Mungkin Suami Mbak Rina,',
		'Di tengah keramaian, terlihat seorang pria berjalan melewati rumah itu. Pria itu mirip dengan maneken yang di depan pintu rumah.',
		'Mbak Rina kemudian mengejar pria itu. Mereka pun berhadapan.',
		'ri Suamiku?',
		'suri Rina?',
		'Mereka langsung berpelukan di sana.',
		'ri Dari mana saja dirimu?',
		'suri Ini salahku, aku bekerja di kantor walikota dan diberhentikan secara hormat hari ini. Aku masih ingat walikota menyanjung tempat ini selalu, dan aku tahu bahwa pemiliknya adalah kamu.',
		'Demikianlah yang didengar Idris akan pembicaraan mereka. Semua yang hadir di tempat terenyuh melihat pemandangan itu.',
		'jump Kasus04',
	],
});
