//Script for Kasus04
monogatari.script ({
	'Kasus04': [
		'show background #000',
		'nvl Kasus04',
		'nvl Pembunuhan di Rumah Maneken Lilin',
		'show scene 0817',
		'show background field',
		'Hari kemerdekaan Indonesia. Orang-orang merayakannya dengan meriah, termasuk masyarakat Sukamawar.',
		'id Hari ini, MA Sukamawar sebenarnya diliburkan namun beberapa siswa dari kelas X diminta untuk menghadiri upacara, termasuk aku dan Firdaus.',
		'Sebagai sekolah swasta, aku sangat bersyukur masih bisa membeli jas almamater ini dan mengenakannya dengan bangga.',
		'id Sekarang aku berada di Lapangan Sukamawar, satu-satunya lapangan yang ada di kota kecil ini berdasar pernyataan Firdaus.',
		'id Pada barisan MA Sukamawar, aku berdiri bersebelahan dengan Firdaus di belakang.',
		'id Waktu menunjukan pukul 08:30 saat melihat jam tanganku, dan upacara tepat dimulai sekarang.',
		'Berbagai prosesi dilaksanakan, salah satunya masuknya inspektur upacara.'
		'id Itukah wali kota kita?',
		'fir Ya, setauku nama beliau Mahmud.',
		'Kemudian salah satu bagian dari prosesi adalah penaikan bendera',
		'id Aku ditakjubkan dengan pasukan pengibar akan keserasian mereka.',
		'Kepada Sang Merah Putih, hormat, gerak!',
		'id Aku langsung menghormati bendera Indonesia, sambil mendengar nyanyian Indonesia Raya sampai selesai.',
		'Tegak, gerak!',
		'id Turunlah tangan dari kepalaku. Menandakan Sang Merah Putih telah sampai ke puncak tiang.',
		'Waktu terus berlalu, sampai upacara selesai dan wali kota pulang.',
		'Banyak orang juga pulang, namun ada yang tetap berada di lapangan.',
		'fir Mereka yang tidak pulang akan mengikuti atau menyaksikan lomba tahunan yang akan diadakan. Lomba tersebut bersifat terbuka dan boleh diikuti oleh siapa saja.',
		'fir Apakah kamu ingin ikut, Idris?',
		'id Tidak, aku menonton saja.',
		'Kondisi Idris kurang sehat pada hari itu.',
		'Idris dan Firdaus pun memutuskan untuk tinggal di sana untuk menonton.',
		'ap Hei, Juna! Bukankah kamu sudah ditentukan untuk ikut lomba panjat pinang? Kenapa kamu memaksa untuk ikut lomba dayung?',
		'sep Benar kata Aprillia, kalau sudah ditentukan, kamu tidak boleh mengikuti lomba lain. Itu kan sudah peraturan!',
		'ap Kamu, Septiana, kamu juga kalau ikut lomba dayung, jangan ikut bungee jumping!',
		'ap Dimana Febri? Dia seharusnya ke sini?',
		'feb Aku di sini dari tadi, Lia!',
		'nov Kalian, berhentilah berdebat! Aku muak mendengar ini!',
		'jun Diam kamu Noval!',
		'Perdebatan itu terdengar di belakang Idris dan Firdaus. Idris hanya memandang mereka dari jauh. Dia mencoba mengenali siapa yang dimaksud mereka.',
		'fir Mereka membahas apa?',
		'Sepertinya Firdaus juga penasaran dengan apa yang diperdebatkan mereka.',
		'id Sepertinya pembagian lomba.',
		'Idris hanya berasumsi.',
		'fir Apakah berarti mereka satu kelompok atau satu tim?',
		'id Kurasa iya.',
		'Idris dan Firdaus menjauh karena tidak ingin mendengar perdebatan. Firdaus menunjuk ke Taman Sukamawar.',
		'show background garden',
		'Idris dan Firdaus ke sana, namun lagi-lagi ada saja orang yang berbicara nyaring.',
		'nin Oke, Selvi, kamu sudah paham kan?',
		'selv Paham, Kak Nina.',
		'nin Tunggu dulu, kamu Mia kan? Kenapa ke sini?',
		'mia Aku muak bersama mereka, aku memilih ikut kalian saja.”',
		'Idris juga mencoba mengenali mereka saat itu sebelum dia dan Firdaus kemudian pergi ke sisi yang lain. Dan tetap saja ada orang yang berdebat sampai Idris mulai kesal.',
		'okt Dimana Aprillia tadi?',
		'jan Aku juga mencarinya lo, Okta.',
		'jul Tuh anak emang kampret.',
		'jan Ya gak usah gitu lah, Juliet.',
		'jul Sudah lama aku kesal, Januar.',
		'id Ini sudah jam sepuluh. Kurasa lombanya akan dimulai sesaat lagi.',
		'Itu hanya alasan Idris untuk pergi mencari ketenangan.',
		'fir Entah kenapa aku ngerasain sesuatu yang buruk akan terjadi lagi hari ini.',
		'fir Perdebatan ini penyebabnya.',
		'id Semoga saja tidak, aku tidak ingin momen sakral ini dikotori oleh tangan-tangan tak beradab.',
		'Idris dan Firdaus pun pergi ke tempat lomba pertama, Kalimawar, sungai terbesar dan terpanjang di kota ini.',
		'show background riverside',
		'mar Mana yang lainnya, Gus?',
		'agu Entahlah Maria, kata Aprillia tadi kita harus menunggu di sini.',
		'mar Sudah capek menunggu, Desi?',
		'des Gak juga.',
		'agu Nah kayaknya sudah mau mulai nih.',
		'Idris mendengar pembicaraan itu sambil mengenali mereka. Namun mereka yang berbicara pergi entah ke mana. Akhirnya Idris bisa tenang.',
		'show background river',
		'id Sungai ini indah ya, Firdaus.',
		'fir Indah, apalagi ketika kelopak mawar berguguran kemudian jatuh ke sungai dan hanyut dibawa arus.',
		'id Kurasa bukan hanya kelopak mawar.',
		'Idris menunjuk sungai.',
		'Di sungai terlihat ada seorang wanita, mengambang dengan tangan mendekap dada sambil memegang mawar. Suasana ricuh seketika.',
		'show background riverside',
		'Orang-orang mulai berlarian menjauh karena ketakutan melihat hal tersebut. Pembicaraan kembali terdengar.',
		'des Mau kemana, Gus?',
		'agu Itu Aprillia, Desi!',
		'des Mana?',
		'show background river',
		'Desi melihat arah Agus berlari yang kemudian beraninya terjun ke sungai yang lebar itu. Beruntung saat itu arusnya tidak begitu kencang, dia berhasil menyelamatkan Aprillia.',
		'show background riverside',
		'Dibawanya ke pinggir sungai dan membaringkannya di siring. Kemudian Maria mencoba memeriksa keadaan Aprillia.',
		'mar Dia sudah mati,',
		'Desi menutup mulutnya, menahan rasa terkejut dan takut atas apa yang dilihatnya.',
		'host Jangan bubar!',
		'Seorang pria yang menjadi pembawa acara langsung mengambil mikrofon.',
		'host Tidakkah kalian mengetahui bahwa perlombaan ini dilakukan secara swadaya? Lagipula, memangnya besok masih tanggal 17? Kami tidak ingin membuang uang dan tenaga setelah menyiapkan semua!',
		'Tim keamanan mulai terlihat dan menghalangi masyarakat bubar.',
		'host Tim kami akan menyelesaikan semua! Tetaplah bersama kami sampai acara selesai karena perlombaan baru saja akan dimulai!',
		'Idris dan Firdaus benar-benar tidak percaya karena mereka--dengan tekad yang kuat--ingin melanjutkan acara meski hal yang baru saja terjadi.',
		'Maria terlihat masih tidak percaya atas apa yang dilihatnya.',
		'mar D-di-Bukankah dia akan tampil setelah ini?',
		'agu Diskusi kemarin menyatakan seharusnya memang begitu, Maria. Namun apa daya, kematiannya ini mengejutkan.',
		'des Bagaimana jika mereka menarik biaya lagi untuk seseorang yang tidak tampil? Siapa yang akan menggantikannya?',
		'agu Entahlah Desi, kita akan menunggu saja mereka tampil di sini.'.
		'id Apakah mereka seperti ini setiap tahun?',
		'Pertanyaan Idris tidak terjawab karena pembawa acara memulai acara begitu saja.',
		'host Bapak-bapak, ibu-ibu, saudara-saudari! Lomba pertama akan segera dimulai!',
		'host Lomba ini kita sebut dengan balap dayung, mempertandingkan dua tim terkuat. Tim Rembulan dan Tim Matahari!',
		'Masyarakat tidak begitu terlihat tertarik untuk menyambut hal tersebut setelah melihat mayat itu, begitu pula aku.',
		'Tapi, karena belum pernah merasakan pengalaman 17 Agustus, Idris memutuskan untuk mencari bangku dan duduk di sana bersama Firdaus yang mengikuti.',
		'Mereka hanya melihat dari sini, meski kurang nyaman untuk memandang.',
		'feb Dari mana saja kalian?'
		'agu Febri, Septiana.',
		'feb Kami mencari-cari kalian.',
		'sep Dan juga Aprillia.',
		'Idris kembali mencoba untuk mengenali mereka karena menyebut nama masing-masing',
		'Desi masih terlihat sedih dan menunjuk mayat. Mereka yang baru datang itu sangat terkejut.',
		'sep Aprillia!',
		'Septiana mengguncang badan Aprillia seakan tidak merelakan kematiannya.',
		'Tak selang berapa saat, tim medis dari pihak panitia datang membawa tandu dan mengangkat Aprillia ke tandu tersebut kemudian membawanya ke ambulans.',
		'fir Benar bukan firasatku, Idris?',
		'id Tidak, itu hanya kebetulan.',
		'host Kalian sudah siap?',
		'jun Belum.',
		'Juna agak kesal. Dia menghela napas sejenak, nampak memikirkan biaya yang harus dikeluarkan jika tidak dilanjutkan.',
		'jun Si-siapa yang akan menggantikannya?',
		'mia Aku',
		'des Mia?',
		'Desi mendekati wanita bernama Mia itu dan menamparnya.'
		'agu Tenanglah Desi.',
		'Mia hanya memegang pipi yang baru saja ditampar itu, dan dia malah tersenyum menyeringai.',
		'jun Dari mana saja kau?',
		'Mia hanya diam.',
		'nov Maukah kamu menggantikan Aprillia?',
		'mia Kalian baru saja memperlakukanku seperti itu, kemudian memintaku untuk ikut kalian? Cih!',
		'Mia kemudian menjauh entah ke mana.',
		'jul Kalau begitu, aku saja.'
		'Juliet datang bersama Okta dan Januar.',
		'jul Juliet? Kamu juga?',
		'okt Kami tidak dianggap?',
		'nov Tenanglah kalian, kita harus menang dalam lomba ini!',
		'Noval mulai bertekad. Mereka berusaha semangat untuk memulai kembali meski baru saja kehilangan satu anggota.',
		'nov Baiklah, sesuai rencana B kita, lomba dayung ini akan diikuti aku, Febri dan Septi. Aprillia bilang dia ingin ikut, tapi setelah kematiannya, aku memilih Juliet karena dia mengajukan diri.',
		'jul Aprillia mati?'
		'jun Iya',
		'jul Baguslah! Sudah lama aku menunggu kematiannya!',
		'jan Hei, Juliet. Bukankah sudah kubilang kamu jangan begitu?',
		'host Perlombaan akan dimulai, harap kepada peserta agar bersiap-siap!',
		'Mereka pun bersiap-siap ke tempatnya meski masih agak murung, sementara Idris dan Firdaus kembali berdiri untuk mendekat ke siring sungai itu.',
		'PRIT!',
		'id Aku sebelumnya berpikir masyarakat akan berteriak menyemangati para peserta lomba namun setelah beberapa hal yang terjadi, harus merelakan tidak mendengar hal itu.',
		'Tiupan peluit yang dilakukan oleh sang pembawa acara menandakan lomba dayung dimulai.',
		'show background river',
		'Terlihat dua perahu, satu berwarna biru dan satu berwarna kuning. Perahu yang berwarna birulah yang dinaiki oleh Noval, Febri, Septi dan Juliet.',
		'host Perahu berwarna kuning sepertinya melaju mendahului perahu berwarna biru.',
		'Terlihat mereka gelabakan di perahu itu. Jika memperhatikan dengan teliti, ternyata perahu mereka bocor. Mereka sepertinya tidak tahu cara menghentikan air yang masuk ke dalam perahu itu.',
		'Perahu itu mulai tenggelam secara perlahan.',
		'Terlihat sebuah masalah, Juliet tidak bisa berenang. Sementara teman-temannya lebih dulu menyelamatkan diri.',
		'Agus mengorbankan dirinya lagi, dan kembali terjun.',
		'Ketika Agus sampai di tengah sungai, tiba-tiba Juliet menghilang dari pandangan mata.',
		'Idris dan Firdaus sangat terkejut melihat hal tersebut.',
		'Agus mulai menyelam, dia berada di dalam air selama lima menit dalam usahanya menemukan Juliet, tapi hasilnya nihil.',
		'Agus kembali ke tepi sungai, mengeringkan badannya dan kembali naik ke siring. Ketika dia berjalan dekat Idris, Idris dapat mendengar napasnya yang ngos-ngosan.',
		'Datanglah tim penyelamat yang masih dari pihak panitia, mereka terjun ke sungai dan membawa Juliet ke tepi.',
		'Terlihat mereka memeriksa keadaannya, kemudian salah satu dari mereka memberi isyarat “X” dengan tangannya. Setelah itu mereka mengangkatnya ke siring dan pembawa tandu sudah menunggu mereka.',
		'Juliet pun dibawa ke dalam ambulans.',
		'Idris teringat ucapan pembawa acara sebelumnya dan menyadari lomba masih berjalan. Mereka yang menaiki perahu kuning berhasil memenangkan lomba dayung ini.',
		'host Dan pemenangnya adalah Tim Matahari!',
		'Dari sini baru diketahui bahwa perahu biru milik Tim Rembulan dan perahu kuning milik Tim Matahari.',
		'show background #000 with fadeIn duration 3s',
		'show background bridge',
		'id Lomba yang kedua adalah bungee jumping, menurut jadwal.',
		'Idris membaca pamflet yang dibagikan saat di lapangan setelah kepulangan para peserta upacara.',
		'Dari desainnya, dapat diketahui bahwa mereka menghabiskan banyak uang untuk perlombaan ini.',
		'fir Apakah di sana?',
		'Firdaus ke puncak jembatan. Jembatan itu bagian dari Kalimawar.',
		'id Apakah tidak ketinggian?',
		'fir Iya juga ya. Pasti sakit kalau jatuh.',
		'host Lomba kedua, bungee jumping akan segera dimulai, harap peserta bersiap-siap di posisi.',
		'fir Apa yang dilakukan dua wanita itu di sana?',
		'Firdaus menengok puncak jembatan.',
		'id Mungkin mereka panitia.'
		'fir Bukan, itu Selvi dan Nina.',
		'Mungkin mereka yang berbicara nyaring di taman itu dan sepertinya Firdaus memperhatikannya.'.
		'id Itu buktinya, mereka turun. Mungkin mereka hanya mengecek talinya.',
		'Kemudian setelah hal itu, para peserta menaiki jembatan dengan memanjat. Salah satu mereka adalah Septi.',
		'fir Tunggu, bukankah dia dilarang ikut bungee jumping?',
		'Kemudian sang pembawa acara menjelaskan peraturan selama peserta bersiap-siap, kulihat Septi tidak sesuai dengan kriteria lomba. Tapi hal itu seharusnya memudahkan dia untuk memenangkan lomba ini.',
		'PRIT!',
		'Tiupan peluit dari sang pembawa acara menghentikan lamunan Idris secara mengejutkan. Mereka mulai terjun.',
		'C-TAK!',
		'Salah satu tali putus, dan itu adalah tali Septi. Ketika lawannya memantul saat ingin menyentuh sungai, maka Septi jatuh secara keras.',
		'Namun tak berapa lama, Septi muncul ke permukaan air. Dia berenang ke tepi sungai. Aku melihat ekspresinya takut namun disertai lega. Dia kembali ke siring.',
		'host Dan pemenangnya adalah Nina!',
		'Noval bangkit dari tempat duduknya, dan mulai memarahi sang pembawa acara.',
		'nov Bukankah tadi jelas-jelas Septi yang duluan?!',
		'host Itu tidak dihitung, karena dia lepas dari tali sehingga dia didiskualifikasi.',
		'nov Talinya putus, bodoh!! Itu salah kalian!',
		'Perdebatan itu semakin menjadi. Kebencian Noval pun membutakannya. Dia mendorong sang pembawa acara dari panggung kecilnya, dan dia jatuh ke tepi sungai.'
		'Kepala terbentur dengan batuan. Dia tewas seketika.',
		'Tim keamanan dari panitia kali ini beraksi lebih cepat. Mereka langsung menangkap Noval dan membawanya ke kejauhan.',
		'Tanpa disadari, Firdaus menghilang dari samping Idris.',
		'show background #000 with fadeIn duration 3s',
		'show background riverside',
		'id Lomba ketiga yang ketiga adalah panjat pinang. Bertempat di Lapangan Sukamawar.',
		'Pamflet itu sangat memberi informasi bagi Idris yang kemudian berdiri secara perlahan, mengingat keadaannya yang sakit.',
		'Idris berjalan ke Lapangan Sukamawar.',
		'show background field',
		'Sesampainya di sana, suasana ricuh. Mereka memandang ke arah yang sama, puncak sebuah batang pinang yang ditancapkan tepat di tengah lapangan.',
		'Ketika Idris memandang ke arah tersebut, ternyata sebuah kepala menggantung di puncak pinang tersebut. Sepertinya itu kepala Febri.',
		'Masyarakat meributkan dimana panitia, apakah kepala itu memang sebagai hadiah panjat pinang.',
		'Kemudian beberapa orang, sepertinya dari panitia, mengambil tangga dan meletakkannya di batang pinang itu, dan mengambil kepala Febri.',
		'Terdengar pembicaraan yang suaranya seperti Idris kenal.',
		'sep Kenapa harus Febri? Padahal dia salah satu yang ikut lomba ini kan?',
		'okt Tenang masih ada aku',
		'Okta datang bersama Juliet dan Januar.',
		'sep Mari kita tentukan orang-orangnya.',
		'Mereka berunding sebentar. Kemudian ada beberapa orang memisahkan diri, yaitu Agus, Januar, Juna dan Okta.',
		'Idris yakin mereka yang mewakili lomba panjat pinang itu.',
		'Okta mengambil nomor undian, karena batang pinang hanya satu sehingga tidak mungkin dipakai oleh banyak tim secara bersamaan. Terdengar bahwa mereka mendapat urutan terakhir.',
		'Rasa malas Idris muncul, dia memilih berjalan sambil mencari di mana Firdaus.',
		'show background river',
		'Idris kembali ke siring itu. Dia berandai bisa melihat lagi perahu itu, apakah memang bocor atau tidak, tapi perahu itu sudah tenggelam.',
		'Idris memandang ke puncak jembatan.',
		'show background bridge',
		'Idris langsung menuju jembatan itu, berusaha memanjat untuk menuju puncaknya. Memaksakan diriku naik untuk melihat tali yang digunakan untuk bungee jumping itu.',
		'Idris sampai, dari sini aku mulai bisa melihat segalanya. Tali milik Septi memang sengaja diputus, karena terlihat bekas potongan di sisa tali itu. Seandainya tali itu putus, mungkin ujung tali tidak serapi itu. Apalagi ada sedikit darah di tali itu.',
		'Idris melihat ke arah hulu, ternyata sungai ini juga melintasi belakang lapangan Sukamawar. Dia pendapat bahwa Aprillia dibunuh di lapangan itu, ketika semua orang pergi dari sana.',
		'Idris dapat melihat batang pinang itu, ternyata sudah sampai giliran tim yang terdiri atas Agus, Januar, Okta dan Juni. Postur tubuh mereka yang tinggi sangat membantu sehingga mereka cukup membutuhkan empat orang untuk memanjat pinang itu.',
		'Namun ketika Okta hampir meraih puncak pinang itu, pinang itu roboh dan menimpa mereka, aku yang melihat kejadian itu ingin rasanya melihat dari dekat.',
		'Idris turun secara perlahan. Ketika sampai, ternyata Firdaus sudah menunggunya di bawah.',
		'fir Kamu kalau sakit, jangan memaksakan dirimu.',
		'id Dari mana kamu tahu aku sakit?',
		'fir Tidak biasanya kamu semalas ini.',
		'id Oh ya, dari mana saja kamu?',
		'fir Aku tadi duluan ke lapangan, ternyata aku menemukan ini.',
		'Firdaus menunjukkan sebuah gunting. Ada bekas darah di ujung gunting itu.',
		'fir Aku juga sempat melihat Selvi dan Nina menghitung uang, aku curiga kepada mereka entah kenapa. Serta beberapa hal lain yang kuketahui.',
		'Idris dan Firdaus memiliki kecurigaan yang sama. Idris mengajaknya untuk pergi ke lapangan dan kali ini, memaparkan bersama.',
		'show background field',
		'Sesampainya di lapangan, terlihat Agus, Januar, Okta dan Juna baik-baik saja, mungkin hanya sedikit lecet. Maria, Septi dan Desi membujuk mereka. Sepertinya mereka benar-benar diliputi rasa kecewa.',
		'id Kira-kira, apa sebab pinang itu roboh?',
		'Firdaus langsung mendekati batang pinang itu, kemudian kembali kepada Idris.',
		'fir Sepertinya bekas tebangan, tapi hanya sedikit.',
		'id Berarti karena banyak tekanan, pinang itu semakin retak dan akhirnya roboh?',
		'fir Bisa jadi. Kita sama-sama tidak melihat kejadiannya langsung.',
		'Terlihat para panitia membersihkan tempat. Idris pun teringat sesuatu, kemudian mendekati mereka.',
		'id Anu, pak! Dimana Anda menaruh kepala tadi?'
		'Salah satu dari mereka memberitahukan bahwa itu di dalam tenda biru sambil menunjuknya.',
		'show background tent',
		'Idris langsung pergi ke tenda biru yang dimaksud, mereka menaruhnya di atas meja. Firdaus mengikuti dan melihatnya juga.',
		'fir Ini kepala Febri bukan? Aku sempat melihatnya.',
		'Idris hanya mengangguk, dan Firdaus seperti menemukan sesuatu di leher Febri. Dia pun mengambil dan menunjukkannya pada Idris.',
		'fir Apa ini? Serpihan kayu?'
		'id Berarti ketika pelaku menebang pinang, Febri melihatnya dan pelaku langsung menebang kepala Febri juga?',
		'fir Bagaimana dengan kapak ini? Apakah ini yang digunakan si pembunuh?',
		'id Bisa jadi. Kita belum tahu.',
		'show background #000 with fadeIn duration 3s',
		'show background field',
		'Idris merogoh sakunya, membuka lipatan pamflet yang hampir kumuh.',
		'id Lomba berikutnya adalah—',
		'mia Hai, guys. Namaku Mia! Kali ini aku menggantikan pembawa acara kita, dan kita akan memulai lomba berikutnya, balap karung! Yey!',
		'id Kurasa aku tidak perlu membacanya lagi, haha.',
		'fir Balap karung bukan? Tapi kok itu karungnya ada isinya ya?',
		'Firdaus menunjuk salah satu karung yang tersandar.',
		'Idris dan Firdaus membuka karung tersebut dan mengeluarkan isinya, ternyata di dalam karung itulah tersimpan tubuh Febri.',
		'Kemudian Nina masuk, ketika dia melihat badan itu, dia sontak berteriak. Masyarakat pun mendekat ke tenda ini, suasana menjadi ricuh.',
		'id Tenanglah!',
		'Setelah mendengar perkataan Idris, mereka semua diam. Tapi tidak dengan Nina.',
		'nin Febri ... siapa yang melakukan ini padamu?',
		'fir KAULAH PELAKUNYA!!',
		'Masyarakat cukup terkejut, mereka memandang ke tenda ini namun syukurlah mereka hanya melihat, tidak mengganggu kami.',
		'Ternyata Firdauslah yang memaparkan kali ini. Idris mengambil waktu istirahat dan membiarkannya.',
		'id Apa alasanmu menuduh Nina sebagai pelakunya?',
		'fir Untuk pembunuhan Febri, memang belum ada bukti. Tetapi, orang yang memutus tali yang digunakan Septi untuk bungee jumping adalah kau!',
		'id Tunggu dulu, saat di atas jembatan itu dia tidak sendirian bukan?',
		'Idris masih ingat hal itu. Orang yang kuduga sebagai panitia. Aku sedikit menyesal tidak mendengarkan Firdaus.',
		'sel Kenapa cuma ngasih segini?',
		'agu Memang begitu kemampuanku.',
		'sel Nina, ayo kita pulang!',
		'fir Dia dibantu oleh dua orang ini.',
		'id Apa kaitan Agus dengan kasus ini?',
		'fir Dia yang merancang semua ini, kemudian membayar Nina sebagai pembunuh dan Selvi sebagai pembantunya.',
		'fir Izinkan aku memaparkan hal ini.',
		'fir Aku yakin pembunuhan Aprillia dan Febri dilakukan oleh Nina. Menurutku, mawar di tangan Aprillia hanyalah keisengan Selvi. Pembunuhan dilakukan dengan memakai gunting yang kemudian dipakai untuk memutus tali yang digunakan Septi dalam bungee jumping.',
		'fir Tenggelamnya Juliet adalah sebuah kecelakaan yang disengaja. Perahu mereka dilubangi, sedangkan mereka tidak sadar. Juliet memang disediakan sebagai pengganti Aprillia.',
		'Firdaus sambil mengeluarkan kertas dari sakunya.',
		'fir Ini adalah rencana tim sekaligus rancangan yang kuyakini ditulis oleh Agus. Tulisan ini kukenali dari tanda tangannya di daftar peserta.',
		'fir Agus sebagai dalang dari semua ini, ditegaskan ketika dia berenang ingin menyelamatkan Juliet, seolah dia tidak berhasil. Dia sebenarnya membiarkan Juliet tenggelam, dibutakan oleh rasa kesalnya. Padahal tim penyelamat berhasil menemukan jasadnya, sedangkan dia berhasil menyelamatkan Aprillia.',
		'fir Sementara pembunuhan Febri, tujuan utama Nina sebenarnya mencelakai tim Rembulan dengan menebang pinang itu. Ternyata baru sedikit, Febri menghampirinya. Karena takut ketahuan, dia langsung menebang kepala Febri dengan kapak yang sama.',
		'id Lalu, apa tugas Selvi?',
		'fir Selvi hanya menemani Nina agar tidak dicurigai.',
		'Idris mengangguk seraya memahami pemaparan Firdaus.',
		'fir Apakah yang kupaparkan itu benar, Nina?',
		'nin Ya, itu benar.',
		'Rupanya masyarakat mendengar pembicaraan kami dan terkejut atas hal itu. Mereka seolah tidak menyangka orang ini pelakunya.',
		'fir Terima kasih telah mengaku.',
		'Firdaus mengambil ponsel dari saku celananya. Tak lama setelah itu, datanglah beberapa orang dari kepolisian. Firdaus berbicara sebentar dengan Brigadir Polisi Kurniawan yang memborgol tangan Agus, Selvi dan Nina. Brigadir Polisi Satu Kuncoro mengambil barang bukti dari tenda ini.',
		'Masyarakat pun mulai berjauhan. Lomba balap karung dibatalkan.',
		'des Aku tidak menyangka Agus dibalik semua ini,',
		'fir Aprillia adalah orang yang menghianatinya dulu. Aku sebagai warga asli Sukamawar, sering melihat mereka bersama sejak 10 tahun yang lalu. Ternyata, baru-baru ini dia selingkuh dan mengambil pacar Nina. Agus pun menghasud Nina untuk membunuh Aprillia sebagai orang yang sama-sama dikhianati, namun dia tidak ingin gratis.',
		'fir Nina pun dibantu temannya, Selvi. Ternyata Selvi lebih materialistis daripada dia.',
		'fir Tahukah kamu, Desi. Mia itu kan teman kalian? Dia kebetulan juga panitia? Dia sudah mengetahui bahwa perahu itu dilubangi, dia juga tahu Juliet yang menggantikan Aprillia itu tidak bisa berenang. Sebenarnya, dia ingin memberitahukan hal itu.',
		'des Lalu, kenapa dia tidak memberitahukannya?',
		'fir Karena adabmu sendiri terhadapnya.',
		'Desi terdiam, menunduk, tersadar atas perbuatannya.',
		'des Aku hanya kesal kenapa dia begitu lama meninggalkan kami.',
		'mia Karena aku ingin hidup sendiri.',
		'Mia menyahut, sepertinya dia mendengarkan sejak Idris dan Firdaus di dalam tenda ini namun baru menunjukkan dirinya.',
		'des Maafkan aku, Mia. Seandainya saja ... mungkin Juliet tidak mati.',
		'Idris dan Firdaus minta izin untuk pulang lebih dulu.',
		'Firdaus singgah sebentar, kemudian membuang kertas ke “Bak Sampah Anorganik.”',
		'fir Idris, sebenarnya kertas itu kutemukan di Bak Sampah Organik namun kuambil. Ternyata isinya adalah rancangan Agus.',
		'id Kapan kau tahu itu tulisan Agus?',
		'fir Ketika aku duluan ke lapangan. Aku bertanya ke Mia karena aku tahu dia. Aku sekadar melihat daftar peserta dari tim Rembulan yang pasti ditulis tangan oleh masing-masing peserta.',
		'id Pasti?',
		'fir Ya! Karena aku selalu mengikuti Lomba 17 Agustus dan baru tahun ini terjadi hal seperti ini.',
		'id Mari kita berharap semoga hal ini tidak terjadi lagi.',
		'jump End'
],
});
