//Script for Kasus02
monogatari.script ({
	'Kasus02' : [
		'show background #000',
		'nvl Kasus 2',
		'nvl Kisah Kelam MA Sukamawar',
		'show scene 0729 with fadeIn 3s',
		'clear',
		'show background school',
		'id Aku berjalan mengelilingi sekolah baruku ini. Aku melakukannya karena mendengar ocehan para guru, tentang sesuatu yang mereka rahasiakan sejak dahulu. Ada hal besar yang akan terjadi hari ini dan saat itu aku belum mengetahuinya.',
		'show background school_hallway',
		'id Saat aku berada di lorong utama, Firdaus menyapaku dari belakang.',
		'fir Idris, mau ke mana?',
		'id Sekadar jalan-jalan. Kamu?',
		'fir Aku ingin mengembalikan kamus ini ke perpustakaan.',
		'id Bolehkah aku ikut?',
		'fir Tentu.',
		'id Kami pun menuju perpustakaan.',
		'show background library',
		'id Sesampainya kami di perpustakaan, ternyata penjaganya tidak ada di sana.',
		'fir Hm, kalau begitu, buku ini kuletakkan di tempat asalnya dulu, nanti saja aku melapor, karena aku bergegas.',
		'Firdaus meletakkan kamus kembali pada raknya.',
		'id Bergegas ke mana?',
		'fir Ke mana lagi kalau bukan ke kelas.',
		'id Bagaimana kalau tinggal sebentar. Ada hal yang ingin kubicarakan, mumpung tidak ada penjaganya di sini.',
		'fir Apa itu?',
		'id Apakah kamu sudah mendengar ocehan para guru tentang sesuatu yang mereka rahasiakan sejak lama?',
		'fir Ya, aku mengetahuinya.',
		'fir Ada sebuah ruangan di sekolah ini yang menyembunyikan semua barang-barang penting. Entah apa maksudnya.',
		'fir Aku sudah lama mengetahuinya, karena almarhum kakakku yang dulu juga sekolah di sini sering menceritakannya.',
		'id Mohon maaf sebelumnya. Bisakah kamu menceritakan lebih tentang meninggalnya kakakmu?',
		'fir Baiklah, jika kamu menginginkannya.',
		'fir Kakakku meninggal di sekolah ini sepuluh tahun yang lalu, saat aku masih berusia enam tahun.',
		'fir Aku merasakan hal aneh. Punggung kakakku dikatakan terluka parah dan ketika jasadnya tiba di rumah, warna kulitnya sudah pucat.',
		'id Aku turut berduka cita.',
		'Idris menunduk saat mengucapkan hal tadi. Saat menunduk, dia melihat bayangan berwarna di bawah meja baca Firdaus. Idris langsung tiarap dan berusaha mengambil barang itu.',
		'id Buku Alumni MA Sukamawar Tahun Ajaran 2009/2010.',
		'Idris membuka buku tersebut dan berhenti pada halaman ketiga.',
		'id Mengenang Andri, salah satu siswa terbaik kami yang tewas di sekolah ini.',
		'fir Itu kakakku.',
		'id Tapi, kenapa mereka memilih kata tewas daripada meninggal. Bukannya lebih halus?',
		'fir Entahlah. Aku tidak tahu.',
		'Tidak lama kemudian, penjaga perpustakaan datang dan melihat buku yang dibaca oleh Idris dan Firdaus.',
		'bam Hei! Apa yang kamu lakukan dengan buku itu?! Sini serahkan!',
		'Idris sontak berdiri dan menyerahkan buku yang dia ambil tadi kemudian diikuti Firdaus.',
		'fir Anu, pak! Saya kemarin kan minjam kamus, barusan saya kembalikan. Saya juga sudah letakkan di raknya.',
		'bam Atas nama?',
		'fir Ahmad Firdaus.',
		'Bambang membuka buku catatannya dan menuliskan hal tersebut.',
		'bam Kalian tahu? Kalian sudah keterlaluan, mengambil buku ini tanpa izin.',
		'bam Maka oleh karena itu, keluar! Jangan kembali lagi!',
		'show background school_hallway',
		'id Firdaus, maafkan aku karena menyebabkan hal ini.',
		'fir Tidak apa-apa.',
		'Idris dan Firdaus hanya berjalan di lorong, dengan keheningan yang terasa.',
		'fir Kamu ingin ke kelas, kah?',
		'id Tidak. Aku mendengar rapat yang akan diadakan nanti berdampak dengan ditiadakannya pelajaran. Mereka katanya akan membahas sebuah hal lebih lanjut.',
		'Firdaus nampak kesal. Idris merasa kekesalannya disebabkan pelajaran hanya dilaksanakan Sabtu kemarin dan tidak lagi setelahnya.',
		'id Mari kita berpikiran positif. Mungkin para guru menyusun ulang jadwal agar tidak tabrakan dengan kelas lain.',
		'id Oh ya, kita kan belum pernah ke lantai dua. Ke sana yuk!',
		'Firdaus menerima ajakan tersebut dan mereka pun menuju lantai dua sekolah.',
		'show background school_rooftop',
		'Sesampainya di lantai dua, ternyata ada bapak kepala madrasah yang berdiri di dekat balkon.',
		'fir Halo, pak.',
		'ba Halo, nak.',
		'ba Sedang apa kalian di sini?',
		'id Kami ingin jalan-jalan.',
		'ba Oh, silakan. Tapi bapak peringatkan jangan pergi ke sana!',
		'Bagus menunjuk ke suatu arah.',
		'fir Siap, pak.',
		'ba Bapak turun dulu ya, kalian hati-hati.',
		'Bagus berjalan menuruni tangga.',
		'id Baik, pak.',
		'id Kira-kira apa yang ada di sana ya?',
		'Idris yang penasaran mendekati arah yang ditunjuk Bagus barusan. Firdaus diam namun mengikutinya.',
		'Idris tetap berjalan sampai tak sengaja terinjak sebuah pintu jebakan sampai hampir terjatuh, tapi Firdaus berhasil menangkapnya.',
		'Idris hanya terduduk sambil memegang dadanya akibat terkejut.',
		'show background gudang_dark',
		'Cahaya masuk ke ruangan tepat di bawah dari pintu ini.',
		'show background school_rooftop',
		'fir Ke mana ini?',
		'Idris teringat kejadian pekan sebelumnya, ketika dia menemani Firdaus mencari tas birunya. Mereka menemukan ruangan yang terkunci sebelumnya, yakni gudang. Nampaknya Firdaus menyadari juga.',
		'fir Tunggu di sini, sementara aku akan turun lebih dahulu ke lantai satu.',
		'Firdaus pun turun ke lantai satu. Idris menunggunya sambil melihat ke dalam ruangan itu.',
		'show background gudang_dark',
		'Cahaya dari atas tidak cukup menerangi ruangan itu. Idris bisa melihat beberapa barang namun tidak tahu apa saja.',
		'show background gudang',
		'Firdaus tiba di ruangan itu, dan Idris bisa melihatnya dari atas. Firdaus membiarkan pintunya terbuka, namun Idris memilih untuk menutup pintu jebakan itu.',
		'show background school_rooftop',
		'Idris sudah menenangkan diri. Dia pun turun dan mencari Firdaus.',
		'show background gudang',
		'Idris sangat terkejut karena tebakannya benar.',
		'Banyak hal menarik yang Idris dan Firdaus temukan di sana. Mulai dari pecahan kaca, patahan kayu, dan beberapa paku yang berlumur darah sampai ke beberapa tali yang terlihat seperti senar gitar, biola dan drum. Terlihat juga di ujung ruangan, tuts piano yang berhamburan serta recorder yang patah.',
		'Meski pintu yang terbuka lebar, tapi baru sebentar di dalam ruangan itu, keringat Idris dan Firdaus mulai bercucuran. Ruangan itu begitu pengap.',
		'show background school_hallway',
		'Idris keluar diikuti Firdaus. Mereka memilih taman kecil di sekolah itu untuk tujuan berikutnya.',
		'show background school_garden',
		'Mereka memilih taman kecil di sekolah itu sebagai tujuan berikutnya. Idris menunjuk sebuah bangku dan duduk di sana. Menikmati angin sepoi-sepoi kemudian berbicara dengan Firdaus.',
		'id Bolehkah aku membicarakan tentang kakakmu?',
		'id Sejak melihat buku alumni itu, aku berpikir bahwa kakakmu sebenarnya terbunuh.',
		'fir Aku juga berpikir demikian.',
		'fir Setelah melihat apa yang kita temukan tadi, aku rasa kita menemukan buktinya. Luka di punggungnya, aku tahu sebabnya.',
		'id Tapi menurutmu, siapa pelakunya?',
		'fir Menurutku bapak penjaga perpustakaan itu. Gelagat beliau begitu aneh saat kita di sana. Itu membuatku sangat curiga.',
		'id Aku malah berpendapat bahwa bapak kepala sekolah pelakunya.',
		'fir Apa alasanmu menganggap beliau pelakunya?',
		'id Masih ingat ketika kita ke lantai dua tadi?',
		'fir Ya, tentu.',
		'id Jika beliau memperingatkan kita untuk jangan pergi ke ujung, maka beliau akan memastikan agar kita tidak pergi ke sana.',
		'id Ternyata, beliau malah turun. Seolah ingin membunuh kita.',
		'id Bagaimana jika hal yang sama terjadi dengan kakakmu?',
		'Idris dan Firdaus terdiam sejenak. Terasa angin bertiup semakin kencang.',
		'Kelopak-kelopak mawar gugur dan beterbangan. Salah satunya mengenai wajah Idris dan dia mengambilnya.',
		'id Layu.',
		'fir Tunggu, jika kakakku dibunuh oleh kepala madrasah, kenapa dia membanggakan prestasi olimpiade Jepang itu?',
		'fir Seharusnya apa yang dilakukan kakakku adalah prestasi terhebat yang pernah diraih oleh MA Sukamawar ini.',
		'fir Mungkin mereka menutupi meninggalnya ibuku, yang bisa saja dibunuh di hari yang sama.',
		'id Meninggalnya ibumu?',
		'Firdaus hanya diam, namun dia nampak begitu marah dengan kepala madrasah.',
		'show background school',
		'Tiba-tiba di tengah keheningan, terdengarlah bunyi sirene mobil polisi mengarah ke MA Sukamawar.',
		'Beberapa polisi keluar dari mobil dan mulai berjalan ke arah ruang kepala madrasah.',
		'Kemarahan Firdaus nampak mulai membutakannya. Dia berlari, mengarah ke salah satu polisi, entah bagaimana caranya bisa mengambil pistol yang dipegang di tangan kanannya dan menuju ruangan kepala madrasah.',
		'Polisi mulai mengejarnya, begitu juga Idris. Namun Firdaus berhasil masuk kantor kepala madrasah dan—',
		'show background school_hallway',
		'Dor!',
		'show background school',
		'Idris cukup terkejut dengan bunyi tembakan itu sehingga dia merasa pengejarannya gagal total.',
		'show background school_hallway',
		'kur Apa yang kamu lakukan, dik?',
		'Anehnya, malah kepala madrasah yang dibawa keluar dengan tangan diborgol.',
		'id Tunggu, apa yang terjadi barusan?',
		'Siswa sempat berkumpul dan heboh, namun setelah melihat kejadian barusan, mereka mulai berjauhan dari lorong.',
		'show background room_headmaster',
		'Akhirnya, Idris dapat dengan mudah masuk ruangan itu dan menemukan Firdaus yang berdiri tegak, seolah kehilangan kesadaran.',
		'Idris mendekati meja kepala madrasah, terdapat hitungan mundur yang hampir berakhir di komputernya.',
		'Idris sangat terkejut dan panik. Dia sangat mengenal hitungan mundur yang terus berjalan di komputer itu untuk bom waktu. Kepanikan Idris melupakan apa yang pernah dia pelajari.',
		'id Firdaus!',
		'fir Peluru kosong....',
		'id Persetan dengan hal itu! Kita dalam bahaya! Ada bom waktu! Matikan itu!',
		'fir Aku gak bisa! Aku belum pernah belajar!',
		'id Kalau begitu, kita keluar. Cari guru yang bisa!',
		'show background school_hallway',
		'Idris dan Firdaus pergi ke ruang guru.',
		'show scene room_teacher',
		'centered Kosong.',
		'show background room_teacher',
		'Idris mencurigai bahwa rapat yang para guru adakan sebelumnya hanya memberitahu bahwa akan terjadi ledakan. Ocehan yang mereka bahas sejak pagi hari.',
		'show background school',
		'Tepat mobil polisi meninggalkan madrasah kami, terjadilah ledakan sampai terdengar dentuman nyaring yang mengherankan berasal dari gudang dan merusak perpustakaan. Api masih membakar dan asapnya membumbung.',
		'show background school_hallway',
		'fir Ah, seandainya kita sempat mengambil barang-barang tadi, itu bisa menjadi bukti betapa kelam sebenarnya madrasah ini.',
		'Idris berusaha menenangkan Firdaus saat itu.',
		'show background school',
		'Tak lama kemudian, terdengar lagi suara sirene, namun kali ini pemadam kebakaran. Mereka datang untuk menyirami ruangan yang terbakar itu. Tapi secara tidak langsung, barang—yang bisa saja menjadi bukti kata Firdaus itu—hangus tiada bersisa.',
		'show scene #000 with fadeIn 3s',
		'jump Kasus03',
	],
});