// Action for Messages
monogatari.action ('Message').messages ({
    'thank_you': {
        title: 'Terima Kasih!',
        subtitle: 'Terima kasih kepada Anda karena telah mengikuti sejauh ini.',
        body: 'Pantau terus Facebook @mnafisalmukhdi1 untuk kabar mengenai pembaruan karya ini.'
    }
});


// Assets for Scenes and Backgrounds
monogatari.assets ('scenes', {
	'pg13': 'pg13.png',
	'author': 'author.png',
	'0715': '0715.png',
	'0716': '0716.png',
	'0717': '0717.png',
	'0729': '0729.png',
	'school': 'school.jpg',
	'school_hallway': 'school_hallway.jpg',
	'school_rooftop': 'school_rooftop.png',
	'door_gudang': 'door_gudang.png',
	'gudang': 'gudang.jpg',
	'gudang_dark': 'gudang_dark.png',
	'stage': 'stage.jpg',
	'stage_dark': 'stage_dark.png',
	'chairs': 'chairs.jpg',
	'locker': 'locker.jpg',
	'door_lib': 'door_lib.png',
	'library': 'library.png',
	'door_musala': 'door_musala.png',
	'musala': 'musala.jpg',
	'musala_bag': 'musala_bag.png'
	
});

// Characters
monogatari.characters ({
	'id' : {
		name: 'Idris',
		color: '#4682B4',
	},
	'fir' : {
		name: 'Firdaus',
		color: '#9ACD32',
	},
	'mus' : {
		name: 'Mustafa',
		color: '#00008B',
	},
	'za' : {
		name: 'Zain',
		color: '#1E90FF',
	},
	'ba' : {
		name: 'Bagus',
		color: '#CD853F',
	}
});

// Component
monogatari.component ('main-screen').template (() => {
    return `
        <h1><img src="https://res.cloudinary.com/mnam23/image/upload/v1611279509/ds_logo.png" alt="Detektif Sekolahan" title="Detektif Sekolahan"></h1>
        <main-menu></main-menu>
    `;
});

// Configuration for Credits
monogatari.configuration ('credits', {
		"Special Thanks to": {
		"The Only One God": "Allah", 
		"My friends": ["Muhammad Najib", "Radian"],
	},
	"Developers": {
		"Artist": "AvatarMaker.com",
		"Writer": "mnafisalmukhdi1",
	},
});

// Script
monogatari.script ({
	'_SplashScreen': [
	'show scene pg13 with fadeIn duration 3s',
	'wait 3000',
	'show scene author with fadeIn duration 3s',
	'wait 3000',
        'end'
	],
	'Start': [
	'centered Keseluruhan cerita hanyalah fiksi. Kesamaan nama tokoh dan tempat bukanlah sebuah kesengajaan. Tidak ada maksud untuk menyudutkan pihak manapun.',
	'jump Kasus01'
    	],
	'Kasus01': [
		'nvl Kasus 1',
		'nvl Pertemuan',
		'show scene 0715 with fadeIn duration 3s',
		'id Sekolah masuk serentak hari ini, termasuk yang baru bagiku, MA Sukamawar.',
		'show background school',
		'id Aku memasuki sekolah ini karena terkena zonasi, rumahku yang tepat di perbatasan antara Kota Sukamawar dengan Kota Kebun Melati dikatakan lebih dekat ke MA Sukamawar daripada MA Kebun Melati.',
		'id Padahal karena aku kelahiran Kebun Melati, tentu saja aku bersekolah di sana. Tapi sistem zonasi yang disepakati oleh kedua walikota memilihku untuk berada di Sukamawar.',
		'id Aku belum mengenal Sukamawar sepenuhnya, kecuali namanya saja. Maka, aku orang baru di sini, dan aku dipenuhi dengan kebingungan.',
		'id Pagi itu dilaksanakanlah upacara penaikan bendera. Dengan penyampai amanat seorang pria, kutebak itu kepala sekolah, karena beliau menyampaikan selamat datang dan membanggakan unggulnya MA Sukamawar.',
		'id Dia mengingat-ingatkan prestasi zaman dulu, salah satu di antaranya adalah seorang siswa yang memenangkan olimpiade di Jepang.',
		'id Pembahasan ini sebenarnya menarik, namun aku merasa bosan. Kebosanan ini membuatku melalui waktu secara tidak sadar.',
		'id Upacara selesai. Kami disuruh menuju ruang multiguna.',
		'show background chairs',
		'id Kami dipersilahkan duduk. Aku memilih kursi tengah.',
		'show background stage',
		'mus Halo semua!',
		'show background chairs',
		'Halo!',
		'show background stage',
		'mus Perkenalkan, nama kakak Mustafa. Kakak adalah ketua OSIS di MA Sukamawar ini. Salam kenal ya!',
		'za Halo, namaku adalah Zain, aku wakil ketua OSIS. Senang bertemu dengan kalian!',
		'mus Setiap tahun, sekolah ini mengadakan Masa Taaruf Siswa Madrasah, atau yang disingkat Matsama. Acara ini diselenggarakan agar kita bisa mengenal, dari siswa sampai sekolah ini sendiri.',
		'mus Dan tahun ini, kami dipercaya sebagai penyelenggara. Doakan juga acara ini berjalan dengan lancar, semoga.',
		'za Apa maksudnya?',
		'za Ya, acara pertama kita selesai. Sepertinya kita juga tidak perlu sambutan kepala sekolah mengingat beliau yang menyampaikan amanat tadi. Maka tidak ada acara lagi selain berkenalan. Silahkan mulai dari teman di samping!',
		'za Kalian diharuskan selalu berjalan beriringan dengan salah satu teman baru kalian, agar lebih memperat pertemanan kalian.',
		'za Nanti juga kalian boleh menunjukkan bakat pada besok hari. Sampai jumpa.',
		'show background chairs',
		'id Aku sangat canggung saat itu, belum berani walau sebatas menyebutkan nama. Aku hanya terus menunduk.',
		'Hai!',
		'id Oh?',
		'fir Namaku Ahmad Firdaus. Namamu siapa?',
		'id Namaku Muhammad Idris.',
		'fir Kamu dari mana?',
		'id Aku dari Kota Kebun Melati.',
		'fir Kalau aku asli dari Sukamawar, senang berkenalan denganmu.',
		'id Firdaus menjulurkan tangannya, pertanda ingin menjabat. Aku menyambutnya perlahan karena gugup. Sesingkat itu perkenalanku.',
		'id Namun pertemuan itu, adalah awal dari segalanya.',
		'show background stage',
		'za Sudah waktu istirahat. Sila makan!',
		'id Kami pun bergerak menuju tempat penaruhan barang. Firdaus nampak mencari sesuatu.',
		'show background locker',
		'id Apa yang kamu cari?',
		'fir Tasku. Warnanya biru dan aku menaruhnya di belakang.',
		'fir Bagaimana bisa hilang? Sedangkan kita saja diam di kursi sejak awal?',
		'id Berarti itu disengaja.',
		'fir Apa maksudmu?',
		'id Cobalah cari, mungkin aku bisa menemanimu.',
		'show background school',
		'id Kami mulai mencari. Wajah Firdaus terlihat gelisah.',
		'show background door_lib',
		'id Kami mencari di perpustakaan.',
		'show background library with fadeIn 3s',
		'centered Tidak ada di sini.',
		'show background door_gudang',
		'id Kami mencari di ruangan sebelahnya.',
		'centered Terkunci.',
		'show background door_musala',
		'id Kami terus berjalan sampai ke musala.',
		'show scene musala_bag with shake 1s',
		'vibrate 200',
		'fir Tasku!',
		'show background musala',
		'id Firdaus langsung membukanya, dan menunjukkan wajah lega setelahnya. Aku melihat juga beberapa barang juga terletak di sini.',
		'fir Kurasa kamu benar. Ini seperti disengaja.',
		'show scene 0716 with fadeIn duration 3s',
		'id Sekarang adalah hari kedua dari acara Masa Taaruf Siswa Madrasah, juga sekolahku di tingkat MA.',
		'show background stage',
		'za Halo semuanya!',
		'show background chairs',
		'Halo!',
		'show background stage',
		'za Hari ini kita melanjutkan acara kita, dan sesuai janji kakak, kalian boleh menunjukkan bakat kalian.',
		'show background chairs',
		'Semua bertepuk tangan. Seolah bergembira atas apa yang akan mereka tonton sebentar lagi.',
		'show background stage_dark',
		'Lampu padam tiba-tiba. Ruangan menjadi gelap dan suasana ricuh.',
		'Sebuah lampu menyorot Zain yang diseret dengan mulut dan mata ditutup tangan pelakunya.',
		'Lampu sorot padam.',
		'show background stage',
		'Beberapa saat kemudian, lampu ruangan menyala lagi dan Zain menghilang.',
		'Anggota OSIS lainnya mulai gelabakan. Naiklah salah seorang dari mereka ke podium, dan menyuruh kami agar tetap tenang dan acara unjuk bakat dibatalkan.',
		'Semua siswa yang berada di ruangan tersebut begitu kecewa dan mulai mengejek acara hari ini. Sementara salah satu anggota OSIS itu turun dari podium dan meninggalkan ruangan bersama yang anggota yang lain.',
		'show background chairs',
		'fir Apa tadi barusan?',
		'id Itu disengaja. Seandainya mereka mau, Zain bisa saja <i>diculik</i> lebih awal daripada ini atau kemarin.',
		'fir Bagaimana kalau kita cari di musala? Kemarin kan, kita menemukan tasku di sana.',
		'id Ide bagus!',
		'show background door_musala',
		'id Kami pergi ke musala.',
		'show scene musala with shake 1s',
		'vibrate 200',
		'id Kami menemukan seseorang di sana dengan kepala bertutup kain hitam. Kulepas kain itu, dan ternyata itu memang Zain. Aku juga melepaskan ikatan tali di kaki, mulut dan tangannya.',
		'show background musala',
		'za Apa yang terjadi?',
		'fir Kami pun tidak tahu.',
		'za Tapi terima kasih, kalian menyelamatkanku. Aku hampir saja kehabisan napas gara-gara kain itu.',
		'Zain bersiap untuk pergi.',
		'id Tunggu dulu, ada beberapa hal yang ingin kusampaikan.',
		'za Silakan.',
		'Idris pun melontarkan pertanyaan-pertanyaan sementara Firdaus hanya memandang. Zain saat itu berbaik hati menjawab pertanyaannya.',
		'id Baiklah, sudah jelas pelakunya.',
		'fir Pelaku di balik semua ini?',
		'id Ya, tapi aku menyampaikannya besok, hari ketiga acara kita.',
		'id Maukah Anda bekerja sama dengan kami?',
		'za Tentu, aku sendiri tertarik mendengar siapa pelakunya.',
		'show scene 0717 with fadeIn duration 3s',
		'id Hari ketiga, hari terakhir untuk acara Masa Taaruf Siswa Madrasah.',
		'show background stage',
		'za Halo semua!',
		'za Ini sudah hari ketiga, berarti semua berakhir di sini.',
		'show background chairs',
		'Suasana menjadi ricuh, seolah para siswa tidak ingin kegembiraan ini berakhir begitu saja.',
		'show background stage',
		'za Saya, mewakili OSIS, meminta maaf atas segala kejadian yang terjadi di Matsama ini, dari menghilangnya barang-barang kalian sampai diculiknya aku beberapa hari yang lalu.',
		'za Kami berjanji, kami akan mengungkap siapa orang yang melakukan hal itu, dengan bantuan teman kita yang bernama Muhammad Idris.',
		'Ketika nama Idris dipanggil, dia memberanikan diri untuk berdiri dari tempat duduk dan menuju ke depan. Zain turun dari panggung dan menyerahkan mikrofon kepadanya.',
		'id Perkenalkan, namaku Muhammad Idris, panggil saja Idris. Aku di sini ditunjuk untuk memberitahukan kalian siapa pelaku di balik kejadian-kejadian ini.',
		'id Tapi aku tidak mau sendirian. Aku minta ditemani teman baruku, Ahmad Firdaus.',
		'Uniknya, sepertinya hanya satu orang bernama itu, hanya dia. Firdaus pun berdiri dan pergi mendampingi Idris. Firdaus sempat kebingungan, itu memang salah Idris karena Firdaus belum memberitahukan hal ini lebih awal.',
		'id Pada intinya, ini semua disengaja. Mari kita mulai dengan barang yang menghilang.',
		'id Aku mengambil contoh dari tas biru Firdaus. Dia bercerita bahwa dia menaruh tasnya paling belakang, tertutupi oleh tas lainnya. Ketika dia mencarinya, ternyata menghilang.',
		'id Kami mulai mencari tas itu dan menemukannya di musala, tepat di samping ruangan ini. Di sana juga ditaruh beberapa barang yang sepertinya sudah kalian ambil.',
		'fir Aku menyadari sesuatu yang aneh, hanya barang-barang yang ditaruh paling belakang yang terletak di sana.',
		'id Aku memiliki teori bahwa sebenarnya barang-barang diambil secara acak namun diletakkan di tempat tertentu. Semakin jauh kalian menaruh barang, semakin dekat untuk ditemukan.',
		'id Lanjut untuk yang kedua, penculikan <i>kak</i> Zain.',
		'id Sama seperti menghilangnya barang itu, hal ini disengaja. Buktinya bahwa kejadian ini didramatisasi, padahal mereka bisa saja menculiknya langsung tanpa mengatur pencahayaannya.',
		'id Di sini aku memiliki teori yang hampir mirip dengan sebelumnya, tapi sekarang semakin berat suatu barang, semakin dekat dia ditemukan.',
		'id Lagipula seandainya memang ada penculik, maka <i>kak</i> Zain akan lebih susah untuk ditemukan.',
		'fir Lalu bagaimana caranya dia bisa berada di musala?',
		'id Orang ini menurutku susah dipindahkan oleh hanya satu orang. Orang itu adalah....',
		'id Kak Mustafa! Keluarlah! Saya tahu Anda pelakunya.',
		'mus Wah, kamu benar sekali.',
		'fir Apa alasan kakak melakukan ini?',
		'mus Bertahun-tahun, para siswa tidak pernah menghargai kegiatan Matsama ini, saking tidak menghargainya, mereka memanggilku kembali.',
		'mus Aku baru saja lulus dari MA Sukamawar ini, dan mereka masih memerlukanku. Aku merelakan semuanya demi acara ini. Tapi mereka tidak menghargainya.',
		'fir Tidak begitu, aku menyukai acara ini. Tanpanya, belum tentu aku bertemu dengan teman baruku.',
		'fir Aku yakin, di antara orang-orang di sini, ada orang yang meneruskan ide kreatif Anda. Jika Anda mengarahkannya ke jalan yang benar.',
		'Idris maju dan menyalami Mustafa. Dia nampak kelelahan, dan akhirnya pingsan. Idris mencoba menyanggahnya sekuat tenaga. Kemudian tim PMR membantu dalam hal ini. Mustafa pun dibawa menggunakan tandu keluar dari ruangan.',
		'id Ada apa dengannya?',
		'za Bukankah dia sudah bilang, dia merelakan segalanya?',
		'za Sebenarnya aku juga alumni, dan sejak dulu dia selalu berusaha sampai lupa diri.',
		'za Apa yang dia katakan itu benar, selama kami menjabat, acara Matsama tidak pernah dihargai. Sekarang, dia punya ide, bagaimana kalau acaranya dikacaukan saja. Dan kalian malah lebih menghargainya.',
		'za Aku melihat dengan jelas, ketika Mustafa berpidato, ekspresi kalian menandakan bahwa sebenarnya kalian tidak menginginkannya. Yang kalian inginkan hanya keseruannya.',
		'Zain meminta mikrofon yang dipegang oleh Idris dikembalikan.',
		'za Ya, demikianlah acara kita, berakhir disini. Saya mewakili seluruh anggota OSIS mengucapkan maaf atas banyaknya kesalahan dalam acara ini.',
		'Idris menyalami Zain namun dia memeluk.',
		'za Terima kasih, sekarang semua sempurna.',
		'Zain melepas pelukan dan tersenyum.',
		'Anggota OSIS pun meninggalkan ruangan setelahnya. Idris hanya tersenyum, sementara Firdaus kebingungan. Para siswa mulai meninggalkan ruangan. Idris dan Firdaus mengambil tas mereka di tempat penaruhan barang, sembari keluar.',
		'show background school',
		'fir Apa maksudnya tadi?',
		'Rupanya Firdaus juga mendengar ucapan terakhir Zain.',
		'id Bukankah kubilang, semuanya sudah dirancang. Aku yakin naskah mereka diperbarui beberapa saat sebelum acara karena aku memberitahu pelakunya. Dan seolah aku yang menyempurnakannya.',
		'fir Oh ya, kamu jurusan apa?',
		'id Aku jurusan Agama, kamu?',
		'fir Aku jurusan Bahasa, huft.',
		'id Kenapa?',
		'fir Hanya saja aku berharap kita bisa sekelas dan mengenal lebih lanjut.',
		'id Kita bisa gunakan waktu istirahat untuk berbicara nantinya.',
		'fir Ya, terkadang hidup kita ini perlu diisi.',
		'Idris terlihat bingung dengan perkataan Firdaus.',
		'show scene #000 with fadeIn 3s',
		'wait 1000',
		'jump Tamat'
	],
	'Tamat' : [
		'show background #000',
		'show message thank_you',
		'end'
	],
});
